package com.gl.webforair.core.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-03-06T20:23:18.797+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "WebServiceForAirSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface WebServiceForAirSoap {

    /**
     * 获取每小时站点审核AQI数据<br/>
     *             portId:4(新区办事处)
     */
    @WebResult(name = "GetHourAQIResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetHourAQI", targetNamespace = "http://tempuri.org/", className = "com.gl.webforair.core.webservice.GetHourAQI")
    @WebMethod(operationName = "GetHourAQI", action = "http://tempuri.org/GetHourAQI")
    @ResponseWrapper(localName = "GetHourAQIResponse", targetNamespace = "http://tempuri.org/", className = "com.gl.webforair.core.webservice.GetHourAQIResponse")
    public java.lang.String getHourAQI(
        @WebParam(name = "portId", targetNamespace = "http://tempuri.org/")
        int portId,
        @WebParam(name = "beginTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar beginTime,
        @WebParam(name = "endTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar endTime
    );

    /**
     * 获取每小时站点实时AQI数据<br/>
     *             portId:4(新区办事处)
     */
    @WebResult(name = "GetRealHourAQIResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetRealHourAQI", targetNamespace = "http://tempuri.org/", className = "com.gl.webforair.core.webservice.GetRealHourAQI")
    @WebMethod(operationName = "GetRealHourAQI", action = "http://tempuri.org/GetRealHourAQI")
    @ResponseWrapper(localName = "GetRealHourAQIResponse", targetNamespace = "http://tempuri.org/", className = "com.gl.webforair.core.webservice.GetRealHourAQIResponse")
    public java.lang.String getRealHourAQI(
        @WebParam(name = "portId", targetNamespace = "http://tempuri.org/")
        int portId,
        @WebParam(name = "beginTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar beginTime,
        @WebParam(name = "endTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar endTime
    );
}
