CREATE TABLE AQIData (
 ID INT NOT NULL IDENTITY (1, 1),
 portname VARCHAR(100) DEFAULT '',
 dateTime DATETIME DEFAULT '1970-01-01 00:00:00',
 SO2 FLOAT(10) DEFAULT '',
 SO2_IAQI INT DEFAULT '',
 NO2 FLOAT(10) DEFAULT 0,
 NO2_IAQI INT DEFAULT 0,
 PM10 VARCHAR(50) DEFAULT '',
 PM10_IAQI VARCHAR(100) DEFAULT '',
 CO FLOAT(10) DEFAULT 0,
 CO_IAQI INT DEFAULT 0,
 O3 FLOAT(10) DEFAULT 0,
 O3_IAQI INT DEFAULT 0,
 Recent8HoursO3 VARCHAR(100) DEFAULT '',
 Recent8HoursO3_IAQI VARCHAR(100) DEFAULT '',
 PM2.5 VARCHAR(100) DEFAULT '',
 PM2.5_IAQI VARCHAR(100) DEFAULT '',
 AQIValue INT DEFAULT 0,
 PrimaryPollutant VARCHAR(100) DEFAULT '',
 Class VARCHAR(100) DEFAULT '',
 Grade VARCHAR(100) DEFAULT '',
 HealthEffect VARCHAR(500) DEFAULT '',
 TakeStep VARCHAR(500) DEFAULT ''
);

ALTER TABLE AQIData ADD CONSTRAINT PK_AQIData PRIMARY KEY (ID);


